{% set name = "rdt" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rdt-{{ version }}.tar.gz
  sha256: db83f7f3f4f79bfc38a9fcb8b9b45fdfa1bb7a5e840239d9c4372572945ac3d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.6,<3.9
  run:
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - psutil >=5.7,<6
    - python >=3.6,<3.9
    - scipy >=1.4.1,<2

test:
  imports:
    - rdt
    - rdt.transformers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/RDT
  summary: Reversible Data Transforms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - csala
    - fealho
    - katxiao
    - pvk-developer
