{% set name = "rdt" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rdt-{{ version }}.tar.gz
  sha256: 59933cbefc086189bc1d233c6762506022b288e4869a181644b5a6a19f96e7be

build:
  number: 0
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - wheel
    - python
    - setuptools
    - pytest-runner 6.0.0
  run:
    - python
    - faker >=10
    - numpy >=1.20.0,<2
    - pandas >=1.1.3
    - psutil >=5.7,<6
    - scipy >=1.5.4,<2
    - scikit-learn >=0.24,<2

test:
  imports:
    - rdt
    - rdt.transformers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/RDT
  summary: Reversible Data Transforms
  description: |
    RDT (Reversible Data Transforms) is a Python library that transforms raw data
    into fully numerical data, ready for data science. The transforms are reversible,
    allowing you to convert from numerical data back into your original format.
  license: BUSL-1.1
  license_file: LICENSE
  license_family: Othe
  doc_url: https://docs.sdv.dev/rdt
  dev_url: https://github.com/sdv-dev/RDT 

extra:
  recipe-maintainers:
    - amontanez24
    - fealho
    - pvk-developer
    - frances-h
